### ISSUE TITLE
Implementar o algoritmo para geração de autômatos determinísticos utilizando derivadas

### ISSUE THREAD

**Issue by rodrigogribeiro** [lives-group/automata-language#10]

**Comment by guinasc2** [comment]
Fiz um commit inicial das funções que fazem essa conversão, mas encontrei um problema durante a criação de estados no autômato.
Para testar se um estado já existe, é preciso procurar por uma ER que seja equivalente à que está sendo inserida. 
Dentro do arquivo derivada.rkt, criei uma função para testar equivalência, mas ela ainda está incompleta. Por exemplo, as REs "(a + b) + c" e "a + (b + c)" são equivalentes, mas a função dirá que não são.
Qual seria uma forma melhor de testar equivalência de ERs?

Além disso, gostaria de mais informações sobre o que exatamente a função mk-dfa espera como parâmetros. Ela adicionou um estado de erro E no autômato e fez uma transição de todos os estados para ele. Eu acho que esse estado está redundante com o estado da RE (EMPTY) que também representa um estado de erro. A forma como as transições para o estado E foram escritas também parece diferente de como eu representei as transições durante a conversão de RE para AFD.
